//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpRestaraunt.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dishes_in_order
    {
        public int Id_dishes_in_order { get; set; }
        public Nullable<int> Id_order { get; set; }
        public Nullable<int> Id_dish { get; set; }
        public Nullable<int> Id_user { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Users Users { get; set; }
    }
}
